app.external.service:
  baseUrl: http://localhost:7075
  url:
    product: ${app.external.service.baseUrl}/sec01/product
    promotion: ${app.external.service.baseUrl}/sec01/promotion
    review: ${app.external.service.baseUrl}/sec01/review
    delta: ${app.external.service.baseUrl}/sec02/delta
    jetblue: ${app.external.service.baseUrl}/sec02/jetblue
    frontier: ${app.external.service.baseUrl}/sec02/frontier
    sec03:
      product: ${app.external.service.baseUrl}/sec03/product
      user: ${app.external.service.baseUrl}/sec03/user
      inventory: ${app.external.service.baseUrl}/sec03/inventory
      shipping: ${app.external.service.baseUrl}/sec03/shipping
    sec04:
      product: ${app.external.service.baseUrl}/sec04/product
      user: ${app.external.service.baseUrl}/sec04/user
      inventory: ${app.external.service.baseUrl}/sec04/inventory
      shipping: ${app.external.service.baseUrl}/sec04/shipping
    sec05:
      car: ${app.external.service.baseUrl}/sec05/car
      room: ${app.external.service.baseUrl}/sec05/room
    sec06:
      product: ${app.external.service.baseUrl}/sec06/product
      review: ${app.external.service.baseUrl}/sec06/review
    sec07:
      product: ${app.external.service.baseUrl}/sec07/product
      review: ${app.external.service.baseUrl}/sec07/review
    sec08:
      product: ${app.external.service.baseUrl}/sec08/product
      review: ${app.external.service.baseUrl}/sec08/review

logging.level:
  net.shyshkin: DEBUG

#resilience4j docs: https://resilience4j.readme.io/docs/circuitbreaker
resilience4j.circuitbreaker:
  instances:
    review-service:
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 4
#      minimumNumberOfCalls: 2
      failureRateThreshold: 50
#      waitDurationInOpenState: 10s
      permittedNumberOfCallsInHalfOpenState: 2
      recordExceptions:
        - org.springframework.web.reactive.function.client.WebClientResponseException
        - java.util.concurrent.TimeoutException

