app.external.service:
  baseUrl: http://localhost:7075
  url:
    product: ${app.external.service.baseUrl}/sec01/product
    promotion: ${app.external.service.baseUrl}/sec01/promotion
    review: ${app.external.service.baseUrl}/sec01/review
    delta: ${app.external.service.baseUrl}/sec02/delta
    jetblue: ${app.external.service.baseUrl}/sec02/jetblue
    frontier: ${app.external.service.baseUrl}/sec02/frontier
    sec03:
      product: ${app.external.service.baseUrl}/sec03/product
      user: ${app.external.service.baseUrl}/sec03/user
      inventory: ${app.external.service.baseUrl}/sec03/inventory
      shipping: ${app.external.service.baseUrl}/sec03/shipping
    sec04:
      product: ${app.external.service.baseUrl}/sec04/product
      user: ${app.external.service.baseUrl}/sec04/user
      inventory: ${app.external.service.baseUrl}/sec04/inventory
      shipping: ${app.external.service.baseUrl}/sec04/shipping
    sec05:
      car: ${app.external.service.baseUrl}/sec05/car
      room: ${app.external.service.baseUrl}/sec05/room

logging.level:
  net.shyshkin: DEBUG