app.external.service.url:
  product: http://localhost:7075/sec01/product
  promotion: http://localhost:7075/sec01/promotion
  review: http://localhost:7075/sec01/review
  delta: http://localhost:7075/sec02/delta
  jetblue: http://localhost:7075/sec02/jetblue
  frontier: http://localhost:7075/sec02/frontier

logging.level:
  net.shyshkin: DEBUG